export const PRICING_PLANS = [
  {
    id: "start",
    name: "Start",
    priceMonthly: 29.99,
    priceAnnual: 299.99,
    description: "L'essentiel pour lancer ton activité sereinement.",
    features: [
      "Réservations en ligne",
      "Rappels automatiques",
      "Profil public visible",
      "Dashboard de suivi",
      "Paiement en ligne sécurisé",
      "CA en temps réel",
      "Chat in-app Blyss",
    ],
    includes: null,
    ctaLabel: "Choisir cette offre",
    featured: false,
  },
  {
    id: "serenite",
    name: "Sérénité",
    priceMonthly: 39.99,
    priceAnnual: 399.99,
    description: "Gagne du temps avec des outils d'analyse et de suivi en plus.",
    features: [
      "Portfolio photos",
      "Export des données (CSV / Excel)",
      "Statistiques détaillées",
      "Rappels post-prestation",
    ],
    includes: "Start",
    ctaLabel: "Choisir cette offre",
    featured: true,
  },
  {
    id: "signature",
    name: "Signature",
    priceMonthly: 49.99,
    priceAnnual: 499.99,
    description: "Pilote ton activité comme une pro, jusqu'aux moindres détails.",
    features: [
      "Synchronisation Apple Calendar",
      "Rapports automatiques (hebdo/mensuels)",
      "Prévision du chiffre d'affaires",
      "Analyses de performance",
      "Support prioritaire",
    ],
    includes: "Sérénité",
    ctaLabel: "Choisir cette offre",
    featured: false,
  },
] as const;
